### ISSUE TITLE
Easy Linux Support

### ISSUE THREAD

**Issue by ura43** [sh1nobuu/BitAnime#1]
`ctypes.windll.kernel32.SetConsoleTitleW("BitAnime")` assumes a windows operating system.
By catching the resulting exception, you can easily enable linux support ootb.
I'll make a PR in a few mins

**Comment by ura43** [comment]
Actually, `os.startfile` isn't platform agnostic either.
I adapted the solution from [`this`](https://stackoverflow.com/questions/17317219/is-there-an-platform-independent-equivalent-of-os-startfile) stackoverflow post into a try except format to account for it

**Comment by ura43** [comment]
I successfully downloaded Tokyo Godfathers using my patched version on Linux.
I can't confirm Mac support

**Comment by sh1nobuu** [comment]
I reviewed your code thanks for fixing it man. I appreciate it. I'll merge it now. Thanks again!
