### ISSUE TITLE
as an executable version users it's not downloading anime fast any more

### ISSUE THREAD

**Issue by ReaLJohnBaker** [sh1nobuu/BitAnime#15]
Since today the DL speed is very slow and some EP are failing to download in the chosen quality :X

**Comment by sh1nobuu** [comment]
So sorry for long hiatus, just got my internet back today. Will work on this project and up the fix asap.

**Comment by ReaLJohnBaker** [comment]
@sh1nobuu I think you updated the executable version? i just tried it and it errors out immediately upon launch.
OS: Win7
