### ISSUE TITLE
[Feature Request] Able to Select Video Quality when Downloading

### ISSUE THREAD

**Issue by NevGi-cpu** [sh1nobuu/BitAnime#3]
I always download animes in 480p. Because of not having enough storage on my pc. I tried many other scripts like anime-dl and others available on Github. Most of them are outdated and don't work on the websites they tell it will. And even if it works I can't download the videos of my choosing quality.

**Comment by sh1nobuu** [comment]
Hello, thank you for your suggestion! I'll work on that after finishing the feature that I will be soon finished (removing the 1 to 99 episodes limit).

**Comment by sh1nobuu** [comment]
> 
> 
> I always download animes in 480p. Because of not having enough storage on my pc. I tried many other scripts like anime-dl and others available on Github. Most of them are outdated and don't work on the websites they tell it will. And even if it works I can't download the videos of my choosing quality.

Hi! I added the feature that will let you choose the episode quality if you're interested on trying it out you can find it here https://github.com/sh1nobuu/BitAnime/tree/feature/dynamic-episode-quality (Not yet optimized. The optimize version will be out tom.) Thanks!

**Comment by NevGi-cpu** [comment]
Yes, I'm very much looking forward to trying it. But, I just have to ask will you be maintaining this project in the future too. Since there is so many projects much like this which was good at first but after some time it was left stagnant.

**Comment by sh1nobuu** [comment]
> Yes, I'm very much looking forward to trying it. But, I just have to ask will you be maintaining this project in the future too. Since there is so many projects much like this which was good at first but after some time it was left stagnant.

Yes, I'm planning on maintaining this script since I use this script a lot too so you don't need to worry about it being outdated.

**Comment by sh1nobuu** [comment]
> Hey i can't use git clone to install bitanime and I also can't install requirements using pip install commands you gave

Can you paste here the error?

**Comment by NevGi-cpu** [comment]
#For Bitanime :
PS C:\Windows\system32> git clone https://github.com/sh1nobuu/BitAnime.git
Error:
git : The term 'git' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling
of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ git clone https://github.com/sh1nobuu/BitAnime.git
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], C
   ommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

#For Requirements:
PS C:\Windows\system32> pip install -r requirements.txt
Error:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by sh1nobuu** [comment]
> #For Bitanime :
> PS C:\Windows\system32> git clone https://github.com/sh1nobuu/BitAnime.git
> Error:
> git : The term 'git' is not recognized as the name of a cmdlet,
> function, script file, or operable program. Check the spelling
> of the name, or if a path was included, verify that the path is
> correct and try again.
> At line:1 char:1
> 
> * git clone https://github.com/sh1nobuu/BitAnime.git
> * ```
>     + CategoryInfo          : ObjectNotFound: (git:String) [], C
>    ommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```
> 
> #For Requirements:
> PS C:\Windows\system32> pip install -r requirements.txt
> Error:
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Are you sure you have git install in your pc? You can't install requirements txt if you can't clone the file. An already way to download it is download the zip version.

**Comment by NevGi-cpu** [comment]
yes i have installed git using choco.
![image](https://user-images.githubusercontent.com/60745818/132714232-3ae7cc8e-0d5f-4afc-8c26-78342013404d.png)

**Comment by sh1nobuu** [comment]
> yes i have installed git using choco.
> ![image](https://user-images.githubusercontent.com/60745818/132714232-3ae7cc8e-0d5f-4afc-8c26-78342013404d.png)

Have you tried cloning other repo? because from what i can see your system can't recognized git as a command

**Comment by NevGi-cpu** [comment]
Seems like I needed to refresh the env now i cloned repo but pip still not working
![image](https://user-images.githubusercontent.com/60745818/132722452-cfcde953-7b26-41cf-b909-ac415b88ef88.png)

**Comment by sh1nobuu** [comment]
> Seems like I needed to refresh the env now i cloned repo but pip still not working
> ![image](https://user-images.githubusercontent.com/60745818/132722452-cfcde953-7b26-41cf-b909-ac415b88ef88.png)

after cloning the repo you need to cd to the BitAnime folder

**Comment by sh1nobuu** [comment]
And if you want to use the script with dynamic script you need to clone the feature/dynamic-episode-quality branch

**Comment by NevGi-cpu** [comment]
How do i do that? I tried this:
![image](https://user-images.githubusercontent.com/60745818/132724839-6749e483-cea4-4d73-a51f-e43c654fdd0f.png)

**Comment by sh1nobuu** [comment]
> 
> 
> How do i do that? I tried this:
> ![image](https://user-images.githubusercontent.com/60745818/132724839-6749e483-cea4-4d73-a51f-e43c654fdd0f.png)

if you want to clone a specific branch you can follow this command:
"git clone -b feature/dynamic-episode-quality --single-branch https://github.com/sh1nobuu/BitAnime.git"
after cloning the repo cd to the folder
cd BitAnime then "pip install -r requirements.txt"

**Comment by NevGi-cpu** [comment]
![image](https://user-images.githubusercontent.com/60745818/132725370-7c6ffea4-ec95-4865-b010-b56f9346bd96.png)

Already installed requirements

**Comment by sh1nobuu** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/60745818/132725370-7c6ffea4-ec95-4865-b010-b56f9346bd96.png)
> 
> Already installed requirements

The BitAnime folder already exist in your system try deleting it and then run the command again.

**Comment by NevGi-cpu** [comment]
![image](https://user-images.githubusercontent.com/60745818/132726049-ea89d577-83ec-4ca1-b42f-7146eb2a662b.png)
Now is everything ready? Do I just download and run bitanime.exe or can I run it through PowerShell. How to choose video quality when downloading

**Comment by sh1nobuu** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/60745818/132726049-ea89d577-83ec-4ca1-b42f-7146eb2a662b.png)
> Now is everything ready? Do I just download and run bitanime.exe or can I run it through PowerShell. How to choose video quality when downloading

![image](https://user-images.githubusercontent.com/73153525/132726950-a9c69204-9f35-474d-8725-274d33b5b81f.png)
for the quality, you have 4 option: 1: 360p, 2: 480p, 3: 720p, 4: 1080p.

**Comment by NevGi-cpu** [comment]
Download not starting
![image](https://user-images.githubusercontent.com/60745818/132727368-5ea9c1bc-b516-428b-84ec-e39da5e5f1ed.png)

**Comment by sh1nobuu** [comment]
> 
> 
> Download not starting
> ![image](https://user-images.githubusercontent.com/60745818/132727368-5ea9c1bc-b516-428b-84ec-e39da5e5f1ed.png)

wait for it the site is quite slow to respond therefore the downloading is slow

**Comment by NevGi-cpu** [comment]
There was a Vinland Saga folder created and 5 eps downloaded but their size was 60mb and only the first 5min part of the video was playable.

**Comment by NevGi-cpu** [comment]
It already closed the .exe after that i found above

**Comment by sh1nobuu** [comment]
> 
> 
> It already closed the .exe after that i found above

seems like the code is broken let me check

**Comment by sh1nobuu** [comment]
I'll mention you after I'm done patching it.

**Comment by NevGi-cpu** [comment]
Ok

**Comment by NevGi-cpu** [comment]
Just so you don't misunderstand. I closed the .exe myself. And after that i found the anime folder.

**Comment by NevGi-cpu** [comment]
I tried again and yes although the progress bar isn't moving the size of episode is increasing I think it's working.

**Comment by sh1nobuu** [comment]
> 
> 
> I tried again and yes although the progress bar isn't moving the size of episode is increasing I think it's working.

Thanks for the info man seems like the site itself is at fault, I'm having a hard time downloading an episode with a 360P quality

**Comment by NevGi-cpu** [comment]
The download is working. 
![image](https://user-images.githubusercontent.com/60745818/132736086-6c526b8e-a56d-4bc1-9744-2e5c83cd3ce9.png)
I want to change the default dir where the anime is downloaded. How can I do it

**Comment by sh1nobuu** [comment]
> The download is working.
> ![image](https://user-images.githubusercontent.com/60745818/132736086-6c526b8e-a56d-4bc1-9744-2e5c83cd3ce9.png)
> I want to change the default dir where the anime is downloaded. How can I do it
You can do that by modifying the code in bitanime.py

**Comment by sh1nobuu** [comment]
> The download is working.
> ![image](https://user-images.githubusercontent.com/60745818/132736086-6c526b8e-a56d-4bc1-9744-2e5c83cd3ce9.png)
> I want to change the default dir where the anime is downloaded. How can I do it

"""
    Create a download folder for the anime
    """
        folder = os.path.join(<your-path>, title)
        if not os.path.exists(folder):
            os.mkdir(folder)

**Comment by NevGi-cpu** [comment]
Thanks for everything. And another thing I noticed when I downloaded 2 or 3 720p anime is that some episodes (1 or 2 eps) were in lower-quality like 360p.

**Comment by sh1nobuu** [comment]
> Thanks for everything. And another thing I noticed when I downloaded 2 or 3 720p anime is that some episodes (1 or 2 eps) were in lower-quality like 360p.

Glad to help! Older anime don't have an HD version therefore the script will download what's available

**Comment by NevGi-cpu** [comment]
I mean i was able to download 720p quality from gogoanime.pe web though and the anime was for Vinland saga, Majo no tabitabi, gleipnir all dubbed versions of 2021 animes

**Comment by sh1nobuu** [comment]
> I mean i was able to download 720p quality from gogoanime.pe web though and the anime was for Vinland saga, Majo no tabitabi, gleipnir all dubbed versions of 2021 animes

I see thanks for the feedback I'll look into that!

**Comment by NevGi-cpu** [comment]
> > The download is working.
> > ![image](https://user-images.githubusercontent.com/60745818/132736086-6c526b8e-a56d-4bc1-9744-2e5c83cd3ce9.png)
> > I want to change the default dir where the anime is downloaded. How can I do it
> 
> """
> Create a download folder for the anime
> """
> folder = os.path.join(insert-your-path-here , title)
> if not os.path.exists(folder):
> os.mkdir(folder)

I did change the Inser-your-path here in bitanime.py. I tried with quote and without quote path but after saving the edits and running bitanime.py it will just open and close ASAP.
![image](https://user-images.githubusercontent.com/60745818/132796056-d2ee3ed6-537c-4da8-beb6-8bc509d4585d.png)

**Comment by sh1nobuu** [comment]
Updated version of the script is already in the master branch. I will now close this issue.
