### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by thereal-S** [sh1nobuu/BitAnime#4]
It seems like the script has a problem downloading Animes with over 99 episodes like Naruto or Bleach.

**Comment by sh1nobuu** [comment]
> It seems like the script has a problem downloading Animes with over 99 episodes like Naruto or Bleach.

Hello, are you getting any error? If so, can you paste here the error. Thanks! And which branch did you pull from?

**Comment by thereal-S** [comment]
OH just saw 
"In version 1.1.0, we removed the 1 to 99 episode limit that can be downloaded. Now you can download all episodes of the anime you like."
-sh1nobuu

Then nvm, thanks!

**Comment by sh1nobuu** [comment]
> OH just saw
> "In version 1.1.0, we removed the 1 to 99 episode limit that can be downloaded. Now you can download all episodes of the anime you like."
> -sh1nobuu
> 
> Then nvm, thanks!

No problem man, have fun using the app!
