### ISSUE TITLE
Link Scrapper

### ISSUE THREAD

**Issue by QuantaNeon** [sh1nobuu/BitAnime#5]
This is the most recently updated repo with new gogoanime.pe site and i really like it!
however a feature i really need is outputting the video links rather than directly downloading them and im sure many other people are gonna need it too, so if there is a way u could do that it would be fantastic!

**Comment by sh1nobuu** [comment]
> This is the most recently updated repo with new gogoanime.pe site and i really like it!
> however a feature i really need is outputting the video links rather than directly downloading them and im sure many other people are gonna need it too, so if there is a way u could do that it would be fantastic!

That's a pretty good feature to add thanks for suggesting it, I'll add that feature on the next update.

**Comment by NevGi-cpu** [comment]
Please add the feature to manually set the range of episodes to be downloaded into next update pipeline too.

**Comment by NevGi-cpu** [comment]
Actually, link scrapper can be used to download needed episodes only.

**Comment by QuantaNeon** [comment]
@sh1nobuu 
Thnx!
I was actually working on a small project in which i had to make a video streaming website, so i was looking for a way to get links easily to embed
😅 can it be in this format
ep-no, ep-name, link
Maybe some more like episode size and all, that would make my work soo much easier and thnx again

**Comment by sh1nobuu** [comment]
> @sh1nobuu
> Thnx!
> One more suggestion, it can be in the format
> Genre, series/movie, cover image link, no of eps
> Then anime name, ep no., ep name
> Maybe some more like episode size blah blah
> I actually wantd a database of 200-300 anime for a project, sorry for asking too much
> It will make this the most coated scraper lol

I can make your first suggestion (outputting the dl links) however the second suggestion is quite hard to do it seems like you want me to make an api for your application.

**Comment by sh1nobuu** [comment]
> Please add the feature to manually set the range of episodes to be downloaded into next update pipeline too.

Thanks for the suggestion. This feature is already on the app (in local repo) which needs to be test before pushing it to remote. I'll push it to the remote as soon as the testing is complete.

**Comment by FirstMega** [comment]
Hey sorry! I figured out a way to get the other details, thnx to scraping, and ill look forward to see the dl links feature

**Comment by QuantaNeon** [comment]
Hey sorry for asking too much,however! I figured out a way to get the other details, thnx to scraping, and ill look forward to see the dl links feature
actually i wanted to learn advanced cms, so i took on a tough dynamic data project, so thats why i needed all the details..

**Comment by sh1nobuu** [comment]
Updated version of the script is already in the master branch. I will now close this issue.

**Comment by sh1nobuu** [comment]
> 
> 
> Hey sorry for asking too much,however! I figured out a way to get the other details, thnx to scraping, and ill look forward to see the dl links feature
> actually i wanted to learn advanced cms, so i took on a tough dynamic data project, so thats why i needed all the details..

https://github.com/sh1nobuu/JS0Nime
