### ISSUE TITLE
Sugesstions

### ISSUE THREAD

**Issue by thereal-S** [sh1nobuu/BitAnime#6]
I am a big fan of your work buddy, I taught you might want some suggestions for future features.

Feature 1 - Episode naming: 
would take the name out the URL and and checking if there is a Episode with 0 after "EP" to check and start renaming it
f.e.: https://gogoanime.pe/category/tokyo-revengers
tokyo-revengers-EP01
starting with 01 would be a a nice touch for people who will use it for their personal media library or in general.

Feature 2 - Episode range:
would be nice if there's a possibility to download a specific range of an anime if it failed earlier.

Since the page does not support other languages and the script seems to download highest resolution possible theres nothing else that got in my mind.

I just wanted to share my taught  with you.

BR.

**Comment by sh1nobuu** [comment]
> I am a big fan of your work buddy, I taught you might want some suggestions for future features.
> 
> Feature 1 - Episode naming:
> would take the name out the URL and and checking if there is a Episode with 0 after "EP" to check and start renaming it
> f.e.: https://gogoanime.pe/category/tokyo-revengers
> tokyo-revengers-EP01
> starting with 01 would be a a nice touch for people who will use it for their personal media library or in general.
> 
> Feature 2 - Episode range:
> would be nice if there's a possibility to download a specific range of an anime if it failed earlier.
> 
> Since the page does not support other languages and the script seems to download highest resolution possible theres nothing else that got in my mind.
> 
> I just wanted to share my taught with you.
> 
> BR.

Thanks for the suggestions man I'll add that to the future updates. Thanks again!

**Comment by sh1nobuu** [comment]
Updated version of the script is already in the master branch. I will now close this issue.
