### ISSUE TITLE
[Question] How to download specific set range of episode?

### ISSUE THREAD

**Issue by NevGi-cpu** [sh1nobuu/BitAnime#7]
Depending on your screenshot, It seems we can only enter the number of episodes we manually want to download but, it will only download in ascending order. Like if we enter 5 as you did, most likely it will download from episodes 1-5. I want to download let's say the midsection (4-8) or the last part(20-24) how can I do that?

**Comment by sh1nobuu** [comment]
> 
> 
> Depending on your screenshot, It seems we can only enter the number of episodes we manually want to download but, it will only download in ascending order. Like if we enter 5 as you did, most likely it will download from episodes 1-5. I want to download let's say the midsection (4-8) or the last part(20-24) how can I do that?

Hello. Thanks asking, that feature will be added on the update. Btw, sorry for the slow progress.

**Comment by NevGi-cpu** [comment]
No worries I have already download new unwatched anime worth 3-4 months of watch time so I think there's plenty of time for this feature to come out.

**Comment by sh1nobuu** [comment]
> 
> 
> No worries I have already download new unwatched anime worth 3-4 months of watch time so I think there's plenty of time for this feature to come out.

Feature added on the master branch. You can try using it now.
